version: '3.1'
services:
  stats-server:
    build: ./ewm-stats-service
    image: ewm-stats-service-dock
    container_name: ewm-stats-service-container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_service
      - SERVER_PORT=9090
    depends_on:
      - stats-db


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./ewm-main-service
    image: ewm-main-service-dock
    container_name: ewm-main-service-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main_service
      - SERVER_PORT=8080
      - STATS_SERVER_URL=http://server:9090
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
